name: Test workflow

on: [push, pull_request]

jobs:
  docker-image:
    name: "Build docker image"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up qemu
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all
      - name: Set up docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest
      - name: Run buildx
        run: |
          docker buildx build \
            --tag faucet/test-host:test \
            --platform linux/386,linux/amd64 \
            --file Dockerfile \
            .
